/*
Check for missing backstab-related files
v2.6 should have all 2das in all games, but older versions may not
*/

ACTION_IF !(FILE_EXISTS_IN_GAME ~CRIPPSTR.2DA~) BEGIN
<<<<<<<< .../temp/CRIPPSTR.2DA
2DA           V1.0
0
              0             1             2             3             4             5             6             7             8             9             10            11            12            13            14            15            16            17            18            19            20            21            22            23            24            25            26            27            28            29            30            31            32            33            34            35            36            37            38            39            40
THIEF         0             0             0             0             0             1             1             1             1             2             2             2             2             3             3             3             3             4             4             4             4             5             5             5             5             6             6             6             6             7             7             7             7             8             8             8             8             9             9             9             9
SHADOWDANCER  0             0             0             0             0             0             1             1             1             1             1             1             2             2             2             2             2             2             3             3             3             3             3             3             4             4             4             4             4             4             5             5             5             5             5             5             6             6             6             6             6
ASSASIN       0             0             0             1             1             1             2             2             2             3             3             3             4             4             4             5             5             5             6             6             6             7             7             7             8             8             8             9             9             9             10            10            10            11            11            11            12            12            12            13            13
BOUNTY_HUNTER 0             0             0             0             0             1             1             1             1             2             2             2             2             3             3             3             3             4             4             4             4             5             5             5             5             6             6             6             6             7             7             7             7             8             8             8             8             9             9             9             9
STALKER       0             0             0             0             0             0             0             0             0             0             1             1             1             1             1             1             1             1             2             2             2             2             2             2             2             2             3             3             3             3             3             3             3             3             4             4             4             4             4             4             4

>>>>>>>>
COPY ~.../temp/CRIPPSTR.2DA~  ~override~
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~SNEAKATT.2DA~) BEGIN
<<<<<<<< .../temp/SNEAKATT.2DA
2DA           V1.0
0
              0             1             2             3             4             5             6             7             8             9             10            11            12            13            14            15            16            17            18            19            20            21            22            23            24            25            26            27            28            29            30            31            32            33            34            35            36            37            38            39            40
THIEF         1             1             1             1             2             2             2             2             3             3             3             3             4             4             4             4             5             5             5             5             6             6             6             6             7             7             7             7             8             8             8             8             9             9             9             9             10            10            10            10            11
SHADOWDANCER  1             1             1             1             1             1             2             2             2             2             2             2             3             3             3             3             3             3             4             4             4             4             4             4             5             5             5             5             5             5             6             6             6             6             6             6             7             7             7             7             7
ASSASIN       1             1             1             2             2             2             3             3             3             4             4             4             5             5             5             6             6             6             7             7             7             8             8             8             9             9             9             10            10            10            11            11            11            12            12            12            13            13            13            14            14
BOUNTY_HUNTER 1             1             1             1             2             2             2             2             3             3             3             3             4             4             4             4             5             5             5             5             6             6             6             6             7             7             7             7             8             8             8             8             9             9             9             9             10            10            10            10            11
STALKER       1             1             1             1             1             1             1             1             2             2             2             2             2             2             2             2             3             3             3             3             3             3             3             3             4             4             4             4             4             4             4             4             5             5             5             5             5             5             5             5             6

>>>>>>>>
COPY ~.../temp/SNEAKATT.2DA~  ~override~
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~backstab.SPL~) BEGIN
  COPY ~%files%/backstab.SPL~ ~override~
END



/*
fix lines for some Expanded Classes kits (incorrect values or column numbers)
Fixes an issue when installing a thief kit after these kits, using ADD_KIT_EX.
*/

ACTION_IF !(MOD_IS_INSTALLED ~d2-modfixes.tp2~ 2) BEGIN    // skip if d2-modfixes component is installed

//Kensai (Thief)
ACTION_IF FILE_EXISTS ~override/CLABUSKT.2DA~ BEGIN
  COPY_EXISTING ~BACKSTAB.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USKT00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USKT00 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~CRIPPSTR.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USKT00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USKT00 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~SNEAKATT.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USKT00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USKT00 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7~
    PRETTY_PRINT_2DA
  BUT_ONLY
END

//Vampyre
ACTION_IF FILE_EXISTS ~override/CLABUSVA.2DA~ BEGIN
  COPY_EXISTING ~BACKSTAB.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USVA00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USVA00 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~CRIPPSTR.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USVA00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USVA00 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~SNEAKATT.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USVA00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USVA00 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4~
    PRETTY_PRINT_2DA
  BUT_ONLY
END

//Seducer
ACTION_IF FILE_EXISTS ~override/CLABUSSD.2DA~ BEGIN
  COPY_EXISTING ~BACKSTAB.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSD77~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSD77 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~CRIPPSTR.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSD77~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSD77 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~SNEAKATT.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSD77~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSD77 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4~
    PRETTY_PRINT_2DA
  BUT_ONLY
END

//Shapechanger
ACTION_IF FILE_EXISTS ~override/CLABUSSC.2DA~ BEGIN
  COPY_EXISTING ~BACKSTAB.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSC00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSC00 1 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~CRIPPSTR.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSC00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSC00 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6~
    PRETTY_PRINT_2DA
  BUT_ONLY
  
  COPY_EXISTING ~SNEAKATT.2DA~ ~override~
    LPF 2da_find_row_delete STR_VAR row_name = ~USSC00~ RET row_number columns END
    INSERT_2DA_ROW row_number columns ~USSC00 1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7~
    PRETTY_PRINT_2DA
  BUT_ONLY
END

END


/*
*/