/*
Crosskit effects
*/


//Healing Blood (%bloodtypea%) can remove bleeding effects

ACTION_IF (%nobloodminister% = 0) BEGIN

  ACTION_FOR_EACH ~bleeding~ IN ~%bloodletter%~ ~%splinteringshot%~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%bleeding%.SPL~) BEGIN
      COPY_EXISTING ~%bloodtypea%.SPL~  ~override~
        LPF CLONE_EFFECT INT_VAR multi_match=1 match_timing=1 match_parameter2=0 opcode=321 STR_VAR resource=~%bleeding%~ END
      BUT_ONLY
    END
  END

END