//Full Metal Jaguar FM


ACTION_IF (nofullmetaljaguarfm = 0) BEGIN


//Remove specialist bonus slots
COPY ~%passives%/fewerspells1.SPL~  ~override/%e6%.SPL~
COPY ~%passives%/opcode206.SPL~     ~override/%e7%.SPL~    // only relevant for 5e casting mod
  LPF ALTER_EFFECT STR_VAR resource=~d5z0slt~ END
  LPF CLONE_EFFECT STR_VAR resource=~D5ZMSLT~ END


//Multiclass import fix
LAF d2_mc_import_fix INT_VAR amount=1  STR_VAR spell=~%s1%~ new_spell=~%#1%~ END
LAF d2_mc_import_fix INT_VAR amount=2  STR_VAR spell=~%s1%~ new_spell=~%#2%~ END
LAF d2_mc_import_fix INT_VAR amount=3  STR_VAR spell=~%s1%~ new_spell=~%#3%~ END
LAF d2_mc_import_fix INT_VAR amount=4  STR_VAR spell=~%s1%~ new_spell=~%#4%~ END
LAF d2_mc_import_fix INT_VAR amount=5  STR_VAR spell=~%s1%~ new_spell=~%#5%~ END
LAF d2_mc_import_fix INT_VAR amount=6  STR_VAR spell=~%s1%~ new_spell=~%#6%~ END
LAF d2_mc_import_fix INT_VAR amount=7  STR_VAR spell=~%s1%~ new_spell=~%#7%~ END
LAF d2_mc_import_fix INT_VAR amount=8  STR_VAR spell=~%s1%~ new_spell=~%#8%~ END
LAF d2_mc_import_fix INT_VAR amount=9  STR_VAR spell=~%s1%~ new_spell=~%#9%~ END
LAF d2_mc_import_fix INT_VAR amount=10 STR_VAR spell=~%s1%~ new_spell=~%#a%~ END


//Array for import fix
ACTION_CLEAR_ARRAY ~import_fix_array~
ACTION_DEFINE_ASSOCIATIVE_ARRAY import_fix_array BEGIN
  ~%#1%~  => 5     // ghostwalker
  ~%#2%~  => 10
  ~%#3%~  => 15
  ~%#4%~  => 20
  ~%#5%~  => 25
  ~%#6%~  => 30
  ~%#7%~  => 35
  ~%#8%~  => 40
  ~%#9%~  => 45
  ~%#a%~  => 50
END


//Ability tables
COPY ~inlined/d2clab.2DA~  ~override/%fullmetaljaguar%F.2DA~
  LPF d2_kit_ability_adder INT_VAR passive=1 STR_VAR resource=~%e1%~ END
  LPF d2_kit_ability_adder INT_VAR passive=1 STR_VAR resource=~%e2%~ END
  LPF d2_kit_ability_adder INT_VAR level=8 passive=1 STR_VAR resource=~%e3%~ END
  LPF d2_kit_ability_adder INT_VAR level=8 passive=1 STR_VAR resource=~%e4%~ END
  LPF d2_kit_ability_adder INT_VAR level=5 multi=1 increment=5 STR_VAR resource=~%s1%~ END

  //import fix (BG2, ToB, SoD)
  PHP_EACH import_fix_array AS file => level BEGIN
    LPF d2_kit_ability_adder INT_VAR level=level passive=1 STR_VAR resource=~%file%~ END
  END

COPY ~inlined/d2clab.2DA~  ~override/%fullmetaljaguar%M.2DA~
  LPF d2_kit_ability_adder INT_VAR passive=1 STR_VAR resource=~%e6%~ END
  LPF d2_kit_ability_adder INT_VAR passive=1 STR_VAR resource=~%e7%~ END


//Kit function
LAF ADD_KIT_EX
  INT_VAR
    kit_class = 7
    mixed = RESOLVE_STR_REF (@101501)
    lower = RESOLVE_STR_REF (@101502)
    help = RESOLVE_STR_REF (@101503)
  STR_VAR
    kit_name = ~D2%kitname%FM~
    clab_base_f = ~%fullmetaljaguar%F.2DA~    // kit abilities added to Fighter table
    clab_base_m = ~%fullmetaljaguar%M.2DA~    // -1 spell slots added to Mage table
    clsrcreq = ~1 1 1 1 1 1 1~                // Usable by all races, if base class is usable
    clascolr = ~24 67 56 2 25~                // blade/jester colors
  RET 
    kit_id
END


//Usability - restrict to splint mail
ACTION_DEFINE_ASSOCIATIVE_ARRAY d2_restrict_armor_array BEGIN
  ~D2%kitname%FM~ => ~splint~
END


END


/* 
*/