//
//


//cast instantly, cast when paused
ACTION_FOR_EACH ability IN 
  ~%blastingsong%~
  ~%boomingsong%~
  ~%dustexplosion%~
  ~%frenzyingflame%~
  ~%enhancedbardsong%~
  ~%rrenhancedsong%~
  ~%rrlingeringsong%~
BEGIN
  COPY_EXISTING ~%ability%.SPL~  ~override~
    LPF ALTER_SPELL_HEADER INT_VAR target=7 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode=146 target=1 STR_VAR resource=d2spell END    // force cast animation (stops singing)
  IF_EXISTS BUT_ONLY
END


/*
*/