/*
Check for missing game resources
run this after variables.tph
*/


ACTION_BASH_FOR ~%kitfolder%~  ~.*~ BEGIN
  ACTION_IF !(FILE_EXISTS_IN_GAME ~%BASH_FOR_FILE%~) BEGIN
    COPY ~%BASH_FOR_FILESPEC%~  ~override~
  END
END


//
ACTION_IF ((IS_AN_INT buildeffects) AND (buildeffects > 1)) BEGIN
  OUTER_TEXT_SPRINT spellitemkit ~%kitid_name%~
  PRINT @13
  ACTION_IF ((IS_AN_INT silentmode) AND (silentmode > 0)) BEGIN SILENT END
END


//
//